### ISSUE TITLE
[Suggestion] - A utility class to remove the buttons that appear on the number type input element.

### ISSUE THREAD

**Issue by bhaveshxrawat** [jamezmca/fantacss#1]
This is an amazing library. I came across this library when you used it in your React Full Course YT video. Everything looks great, the UI, dark mode is awesome. All in all, a great library for someone looking to build a webpage without putting much efforts into CSS.

The number type input elements though could be made to get rid of the buttons that appear by default, used to increment and decrement the value. Although, almost every client of mine, never wanted to see those buttons, it shouldn't be forced on the users. So, a class can be defined with the appropriate rules, so that the users have the choice.

If it is okay, I would like to contribute: this is the codepen. https://codepen.io/bhaveshrawat/pen/GRVrmVP

[CSS Line 486] I have used "buttonless" as the selector to write the rules so that the users can opt in for this behaviour. Works across every browser

![image](https://github.com/user-attachments/assets/ba08bbae-9821-4b95-afb3-319812185917)

**Comment by jamezmca** [comment]
Brilliant suggestion and thanks for the code share! I have integrated these suggestions into the repo :D
